### PR TITLE
Added C++ version of MySaw

### PR DESCRIPTION
**Pull request by cianoc**
I have not renamed the existing MySaw folder because it complicates the pull request.

### CODE REVIEW

**Review by nhthn — CHANGES_REQUESTED** [review]
thanks! the only major problem with this is that there's a naming collision with the other MySaw, so there will be problems if someone installs the entire example-plugins directory. could you rename it to MySaw2 please?

**Comment by cianoc** [comment]
Renamed. Knew I was forgetting something.

**Comment by cianoc** [comment]
bump

**Review by nhthn — APPROVED** [review]

**Comment by nhthn** [comment]
thanks, and sorry about the delay

**Pull request merged**
